#!/bin/bash

interfaces=${BLOCK_INSTANCE//,/ }
wifi=$(echo $interfaces | awk '{print $1}')
ethernet=$(echo $interfaces | awk '{print $2}')

ssid_name=$(iwgetid -r)
wifi_status=$(cat /sys/class/net/${wifi}/operstate)
ethernet_status=$(cat /sys/class/net/${ethernet}/operstate)

if [[ "${wifi_status}" == "up" ]]; then
	if [[ -d "/sys/class/net/${wifi}/wireless" ]]; then
		quality=$(grep ${wifi} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    		if [[ "${quality}" != "" ]]; then
			echo "${quality}% ${ssid_name}"
			exit 0
    		fi
	fi
fi

if [[ "${ethernet_status}" == "up" ]]; then
	echo "eth"
	exit 0
fi

echo "-"
